# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.12.3
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: zecchetto@iiasa.ac.at
include_cli: false
name: MZ
notebook_based_docs: true
package_manager: uv
pandas_doctests: false
plot_dependencies: true
project_description_short: Project to run tests
project_name_human: Unit test prj
project_name_pip: unit-test-prj
project_name_python: unit_test_prj
project_url: https://github.com/mzecc/unit_test.git
track_lock_file: false
